name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Install backend dependencies
      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      # 4️⃣ Install frontend dependencies
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      # 5️⃣ Build frontend
      - name: Build frontend
        run: |
          cd frontend
          npm run build

      # 6️⃣ Start backend server
      - name: Start backend
        run: |
          cd backend
          npm start &
      
      # 7️⃣ Serve frontend build
      - name: Serve frontend
        run: |
          npx serve -s frontend/build &

      # 8️⃣ Wait until app is ready
      - name: Wait for app
        run: |
          for i in {1..40}; do
            if nc -z localhost 3000; then
              echo "✅ App is running!";
              exit 0;
            fi
            echo "⏳ Waiting for app...";
            sleep 3;
          done
          echo "❌ App did not start in time!";
          exit 1;

      # 9️⃣ Run Cypress tests
      - name: Run Cypress
        run: npx cypress run







 




