name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Build app for production
      - name: Build app
        run: npm run build

      # 5️⃣ Serve app in the background
      - name: Serve app
        run: npx serve -s build &

      # 6️⃣ Wait until app is ready (port 3000)
      - name: Wait for app
        run: |
          for i in {1..30}; do
            if nc -z localhost 3000; then
              echo "App is running!";
              exit 0;
            fi
            echo "Waiting for app...";
            sleep 2;
          done
          echo "App did not start in time!";
          exit 1;

      # 7️⃣ Run Cypress tests
      - name: Run Cypress
        run: npx cypress run






 




